// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBalicM2i2pG6cMHyz9AhRwi02nVUJeNXU',
    appId: '1:225413975692:android:ee0ec20a0cf14e7c20f5a9',
    messagingSenderId: '225413975692',
    projectId: 'flutterappchat-78d9a',
    storageBucket: 'flutterappchat-78d9a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldYyYjBf_F_BQiFbI5y_RERON-gbXwNY',
    appId: '1:225413975692:ios:5b456d8a577f592820f5a9',
    messagingSenderId: '225413975692',
    projectId: 'flutterappchat-78d9a',
    storageBucket: 'flutterappchat-78d9a.firebasestorage.app',
    iosBundleId: 'com.example.myflutterproject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldYyYjBf_F_BQiFbI5y_RERON-gbXwNY',
    appId: '1:225413975692:ios:5b456d8a577f592820f5a9',
    messagingSenderId: '225413975692',
    projectId: 'flutterappchat-78d9a',
    storageBucket: 'flutterappchat-78d9a.firebasestorage.app',
    iosBundleId: 'com.example.myflutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcMdKxr-r0aINlwR_Iz1c4WnvZY1gvK74',
    appId: '1:225413975692:web:51689590b798631c20f5a9',
    messagingSenderId: '225413975692',
    projectId: 'flutterappchat-78d9a',
    authDomain: 'flutterappchat-78d9a.firebaseapp.com',
    storageBucket: 'flutterappchat-78d9a.firebasestorage.app',
    measurementId: 'G-V2FCD34YRH',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMdKxr-r0aINlwR_Iz1c4WnvZY1gvK74',
    appId: '1:225413975692:web:51689590b798631c20f5a9',
    messagingSenderId: '225413975692',
    projectId: 'flutterappchat-78d9a',
    authDomain: 'flutterappchat-78d9a.firebaseapp.com',
    storageBucket: 'flutterappchat-78d9a.firebasestorage.app',
    measurementId: 'G-V2FCD34YRH',
  );

}